/**
 * Temporary mailbox for Qwen signup verification.
 *
 * Primary (glm-style): browser inbox at https://tuamaeaquelaursa.com/
 * Fallback APIs: mail.tm / Guerrilla (often blocked by Qwen for delivery)
 */

import type { Page } from "playwright";

export type TempMailProvider =
  | "tuamaeaquelaursa"
  | "mail.tm"
  | "guerrillamail";

export interface TempMailbox {
  email: string;
  provider: TempMailProvider;
  /** mail.tm token */
  token?: string;
  /** guerrilla sid */
  sidToken?: string;
  login?: string;
  domain?: string;
  password?: string;
  /** browser-inbox mode keeps the inbox page open */
  browserInbox?: boolean;
}

export interface TempMessage {
  id: string;
  subject: string;
  from: string;
  text: string;
  html: string;
  receivedAt?: string;
}

export interface VerificationPayload {
  code?: string;
  link?: string;
  message: TempMessage;
}

const URSA_URL = "https://tuamaeaquelaursa.com/";
const BROWSER_INBOX_WAIT_MS = 180_000;

const URSA_SELECTORS = {
  input: "input.email-section-input-email",
  suffix: ".email-section-input-suffix",
  inboxReady: ".all-messages, .the-message, .message-details-body, body",
  inboxList: ".all-messages, .the-message, body",
  messageRow: ".the-message",
  messageFrom: ".the-message-from",
  messageSubject: ".the-message-subject",
  messageBody: ".message-details-body",
};

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

async function fetchJson<T>(
  url: string,
  init?: RequestInit,
  timeoutMs = 15_000,
): Promise<T> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetch(url, {
      ...init,
      signal: controller.signal,
      headers: {
        "user-agent": "qwenbridge-temp-mail/1.0",
        accept: "application/json",
        ...(init?.headers || {}),
      },
    });
    const text = await res.text();
    if (!res.ok) {
      throw new Error(`HTTP ${res.status} ${url}: ${text.slice(0, 200)}`);
    }
    if (!text?.trim()) return [] as T;
    return JSON.parse(text) as T;
  } finally {
    clearTimeout(timer);
  }
}

function randomLocalPart(prefix = "qwen"): string {
  const stamp = Date.now().toString(36);
  const rand = Math.random().toString(36).slice(2, 8);
  return `${prefix}_${stamp}_${rand}`.toLowerCase();
}

function randomPassword(): string {
  return `Qwen@${Math.random().toString(36).slice(2, 10)}Aa1!`;
}

// ─── tuamaeaquelaursa (browser inbox — glm style) ───────────────────────────

export async function createUrsaMailbox(page: Page): Promise<TempMailbox> {
  // Match glm: use the address generated by the site (do NOT invent a local-part).
  // Custom local-parts often break delivery / inbox routing on tuamaeaquelaursa.
  await page.goto(URSA_URL, {
    waitUntil: "domcontentloaded",
    timeout: 45_000,
  });
  await page.waitForSelector(URSA_SELECTORS.input, { timeout: 30_000 });
  await sleep(1_000);

  const input = page.locator(URSA_SELECTORS.input).first();
  let email = "";
  for (let i = 0; i < 12; i++) {
    const name = (await input.inputValue().catch(() => "")).trim();
    const domain = (
      (await page.locator(URSA_SELECTORS.suffix).first().textContent()) || ""
    ).trim();
    if (name && domain) {
      email = domain.startsWith("@")
        ? `${name}${domain}`
        : `${name}@${domain.replace(/^@/, "")}`;
      break;
    }
    // reload for a fresh address if empty
    if (i > 0 && i % 3 === 0) {
      await page.reload({ waitUntil: "domcontentloaded" }).catch(() => {});
      await page.waitForSelector(URSA_SELECTORS.input, { timeout: 15_000 }).catch(() => {});
    }
    await sleep(500);
  }

  if (!email.includes("@")) {
    throw new Error("tuamaeaquelaursa: não foi possível ler o e-mail gerado pelo site");
  }

  const login = email.split("@")[0];
  const inboxUrl = `https://tuamaeaquelaursa.com/${login}`;
  await page.goto(inboxUrl, {
    waitUntil: "domcontentloaded",
    timeout: 45_000,
  });
  await page
    .waitForSelector(URSA_SELECTORS.inboxReady, {
      timeout: BROWSER_INBOX_WAIT_MS,
    })
    .catch(() => {});

  return {
    email,
    provider: "tuamaeaquelaursa",
    login,
    domain: email.split("@")[1],
    browserInbox: true,
  };
}

/**
 * Soft keep-alive for the inbox tab.
 * Prefer a single hard refresh only when explicitly requested — Firebase
 * realtime works once the page is loaded, but a one-shot reload after
 * signup is what makes the Qwen mail actually appear in this SPA.
 */
async function ensureUrsaInboxOpen(
  page: Page,
  login: string,
  options: { hardRefresh?: boolean } = {},
): Promise<void> {
  const target = `https://tuamaeaquelaursa.com/${login}`;
  const current = page.url();
  const onMailbox = new RegExp(
    `tuamaeaquelaursa\\.com\\/${login}(?:/|\\?|#|$)`,
    "i",
  ).test(current);

  await page.bringToFront().catch(() => {});

  if (options.hardRefresh) {
    if (onMailbox) {
      await page
        .reload({ waitUntil: "domcontentloaded", timeout: 45_000 })
        .catch(async () => {
          await page.goto(target, {
            waitUntil: "domcontentloaded",
            timeout: 45_000,
          });
        });
    } else {
      await page.goto(target, {
        waitUntil: "domcontentloaded",
        timeout: 45_000,
      });
    }
    await page
      .waitForSelector(URSA_SELECTORS.inboxList, { timeout: 20_000 })
      .catch(() => {});
    await sleep(800);
    return;
  }

  if (!onMailbox) {
    await page.goto(target, {
      waitUntil: "domcontentloaded",
      timeout: 45_000,
    });
    await page
      .waitForSelector(URSA_SELECTORS.inboxList, { timeout: 30_000 })
      .catch(() => {});
    await sleep(800);
  }

  // Nudge Vuex/Firebase without full reload.
  await page
    .evaluate((loginName) => {
      try {
        const app = (document.querySelector("#app") as any)?.__vue__;
        const store = app?.$store;
        if (store?.dispatch) {
          store.dispatch("connect_to_box").catch?.(() => {});
          store.commit?.("connect_to_box");
        }
        document.dispatchEvent(new Event("visibilitychange"));
        window.dispatchEvent(new Event("focus"));
        if (app?.$route?.params?.email !== loginName && app?.$router?.push) {
          app.$router.push(`/${loginName}`);
        }
      } catch {
        // ignore
      }
    }, login)
    .catch(() => {});
}

/** Return from message detail to the mailbox list without hard reload. */
async function backToUrsaList(page: Page, login: string): Promise<void> {
  const listUrl = `https://tuamaeaquelaursa.com/${login}`;
  const current = page.url();
  // Detail routes look like /login/messageId
  if (
    new RegExp(`tuamaeaquelaursa\\.com\\/${login}/[^/?#]+`, "i").test(current)
  ) {
    await page.bringToFront().catch(() => {});
    await page.goBack({ waitUntil: "domcontentloaded" }).catch(async () => {
      await page.goto(listUrl, {
        waitUntil: "domcontentloaded",
        timeout: 30_000,
      });
    });
    await sleep(600);
  }
}

export async function listUrsaMessages(
  page: Page,
): Promise<Array<{ from: string; subject: string; index: number }>> {
  // Walk Vue tree + Vuex + DOM. Playwright Chromium often has the rows in
  // store/state before (or without) matching CSS selectors.
  const fromState = await page
    .evaluate(() => {
      const out: Array<{ from: string; subject: string; key?: string }> = [];
      const seen = new Set<string>();
      const push = (from: string, subject: string, key?: string) => {
        const id = `${key || ""}|${from}|${subject}`;
        if (seen.has(id)) return;
        seen.add(id);
        out.push({
          from: String(from || "").trim(),
          subject: String(subject || "").trim(),
          key,
        });
      };

      try {
        const roots: any[] = [];
        const appEl = document.querySelector("#app") as any;
        if (appEl?.__vue__) roots.push(appEl.__vue__);
        // also walk any vue roots
        document.querySelectorAll("*").forEach((el: any) => {
          if (el.__vue__ && roots.length < 20) roots.push(el.__vue__);
        });

        for (const root of roots) {
          const store = root?.$store;
          const candidates = [
            store?.state?.messages,
            root?.messages,
            root?.$data?.messages,
            root?.$children?.flatMap?.((c: any) => c.messages || []) || [],
          ];
          for (const list of candidates) {
            if (!Array.isArray(list)) continue;
            for (const m of list) {
              if (!m || typeof m !== "object") continue;
              push(
                m.from || m.sender || m.fromEmail || m.mail_from || "",
                m.subject || m.title || m.mail_subject || "",
                m.key || m.id || m.mail_id,
              );
            }
          }
        }

        // DOM fallback text scrape for .the-message rows
        document.querySelectorAll(".the-message").forEach((row) => {
          const from =
            row.querySelector(".the-message-from")?.textContent || "";
          const subject =
            row.querySelector(".the-message-subject")?.textContent ||
            row.textContent ||
            "";
          push(from, subject);
        });
      } catch {
        // ignore
      }
      return out;
    })
    .catch(() => [] as Array<{ from: string; subject: string }>);

  const rows = page.locator(URSA_SELECTORS.messageRow);
  const count = await rows.count().catch(() => 0);
  const items: Array<{ from: string; subject: string; index: number }> = [];
  for (let i = 0; i < count; i++) {
    const from = (
      (await rows
        .nth(i)
        .locator(URSA_SELECTORS.messageFrom)
        .textContent()
        .catch(() => "")) || ""
    ).trim();
    const subject = (
      (await rows
        .nth(i)
        .locator(URSA_SELECTORS.messageSubject)
        .textContent()
        .catch(() => "")) || ""
    ).trim();
    const rowText = (
      (await rows.nth(i).innerText().catch(() => "")) || ""
    ).trim();
    items.push({
      from: from || rowText.slice(0, 80),
      subject: subject || rowText.slice(0, 120),
      index: i,
    });
  }

  if (items.length > 0) return items;
  if (fromState.length > 0) {
    return fromState.map((m, index) => ({
      from: m.from || "unknown",
      subject: m.subject || "(sem assunto)",
      index,
    }));
  }
  return [];
}

function messageLooksLikeQwen(from: string, subject: string): boolean {
  const blob = `${from} ${subject}`.toLowerCase();
  // Real Qwen subjects seen in the wild: "qwen.ai active mail."
  return /qwen|qwenlm|alibaba|aliyun|activate|active mail|verify|verifica|activa|confirma|security|account/i.test(
    blob,
  );
}

/**
 * Poll tuamaeaquelaursa for the Qwen activation mail.
 *
 * Manual-equivalent that actually works:
 *  1) ONE hard refresh after signup (mail only shows up after refresh)
 *  2) Soft poll without further reloads
 *  3) Optional second refresh only if still empty after ~12s
 *  4) Open Qwen message → click Activate My Account / extract link
 */
export async function waitForUrsaVerificationLink(
  page: Page,
  mailbox: TempMailbox,
  options: {
    timeoutMs?: number;
    pollIntervalMs?: number;
    /** Hard-reload inbox once at start (default true). */
    refreshOnce?: boolean;
    onPoll?: (info: {
      elapsedMs: number;
      messages: number;
      sample?: string;
      refreshed?: boolean;
    }) => void;
  } = {},
): Promise<VerificationPayload> {
  const timeoutMs = options.timeoutMs ?? 180_000;
  // Soft poll — do NOT reload every cycle.
  const pollIntervalMs = Math.max(options.pollIntervalMs ?? 2_500, 1_500);
  const login = mailbox.login || mailbox.email.split("@")[0];
  const started = Date.now();
  const deadline = started + timeoutMs;
  let didInitialRefresh = false;
  let didSecondRefresh = false;

  // After account creation: one refresh so the Qwen mail becomes visible.
  if (options.refreshOnce !== false) {
    await ensureUrsaInboxOpen(page, login, { hardRefresh: true });
    didInitialRefresh = true;
    options.onPoll?.({
      elapsedMs: 0,
      messages: 0,
      sample: "inbox atualizada (1x)",
      refreshed: true,
    });
  } else {
    await ensureUrsaInboxOpen(page, login);
  }

  while (Date.now() < deadline) {
    await backToUrsaList(page, login);
    // Soft focus/nudge only — no reload here.
    await ensureUrsaInboxOpen(page, login);

    const msgs = await listUrsaMessages(page);
    options.onPoll?.({
      elapsedMs: Date.now() - started,
      messages: msgs.length,
      sample: msgs[0]
        ? `${msgs[0].from} | ${msgs[0].subject}`.slice(0, 80)
        : undefined,
      refreshed: didInitialRefresh,
    });

    // Second (and last) refresh if still empty ~12s after the first.
    if (
      msgs.length === 0 &&
      didInitialRefresh &&
      !didSecondRefresh &&
      Date.now() - started >= 12_000
    ) {
      await ensureUrsaInboxOpen(page, login, { hardRefresh: true });
      didSecondRefresh = true;
      options.onPoll?.({
        elapsedMs: Date.now() - started,
        messages: 0,
        sample: "2ª atualização da inbox (última)",
        refreshed: true,
      });
      await sleep(600);
      continue;
    }

    // Only open Qwen-related messages (subject like "qwen.ai active mail.")
    let idx = msgs.findIndex((m) => messageLooksLikeQwen(m.from, m.subject));
    // If the only message is brand-new and list is short, still try it.
    if (idx < 0 && msgs.length === 1) idx = 0;

    if (idx >= 0) {
      const row = page.locator(URSA_SELECTORS.messageRow).nth(idx);
      // Prefer the row's own link when present (SPA route /login/msgId)
      const rowLink = row.locator("a").first();
      if (await rowLink.count().catch(() => 0)) {
        await rowLink.click({ timeout: 8_000 }).catch(async () => {
          await row.click({ timeout: 8_000 }).catch(() => {});
        });
      } else {
        await row.click({ timeout: 8_000 }).catch(() => {});
      }

      await page
        .waitForSelector(URSA_SELECTORS.messageBody, { timeout: 20_000 })
        .catch(() => {});
      await sleep(700);

      const body = page.locator(URSA_SELECTORS.messageBody).first();
      const html = (await body.innerHTML().catch(() => "")) || "";
      const text = (await body.innerText().catch(() => "")) || "";
      const pageHtml = await page.content().catch(() => "");
      const pageText =
        (await page.locator("body").innerText().catch(() => "")) || "";

      // 1) Prefer the visible CTA used by Qwen: "Activate My Account"
      const cta = page
        .locator(`${URSA_SELECTORS.messageBody} a, a, button`)
        .filter({
          hasText:
            /Activate My Account|Activate your account|Ativar (minha )?conta|Verify|Verificar|Confirm|Confirmar/i,
        })
        .first();

      if (await cta.isVisible().catch(() => false)) {
        const href =
          (await cta.getAttribute("href").catch(() => null)) || undefined;
        if (href && /^https?:\/\//i.test(href) && !/tuamaeaquelaursa/i.test(href)) {
          const clean = href
            .replace(/&amp;/g, "&")
            .replace(/&#x2F;/gi, "/")
            .replace(/[),.;\]>]+$/, "");
          return {
            link: clean,
            message: {
              id: `ursa-${idx}`,
              subject: msgs[idx]?.subject || "verification",
              from: msgs[idx]?.from || "",
              text,
              html,
            },
          };
        }

        // CTA without usable href: click and capture navigation/popup.
        const [popup] = await Promise.all([
          page
            .context()
            .waitForEvent("page", { timeout: 8_000 })
            .catch(() => null),
          cta.click({ timeout: 5_000 }).catch(() => {}),
        ]);
        if (popup) {
          await popup.waitForLoadState("domcontentloaded").catch(() => {});
          const url = popup.url();
          await popup.close().catch(() => {});
          if (/qwen|verify|activ|confirm|token=/i.test(url)) {
            return {
              link: url,
              message: {
                id: `ursa-${idx}`,
                subject: msgs[idx]?.subject || "verification",
                from: msgs[idx]?.from || "",
                text,
                html,
              },
            };
          }
        } else {
          await sleep(1_000);
          const current = page.url();
          if (/qwen|verify|activ|confirm|token=/i.test(current)) {
            return {
              link: current,
              message: {
                id: `ursa-${idx}`,
                subject: msgs[idx]?.subject || "verification",
                from: msgs[idx]?.from || "",
                text,
                html,
              },
            };
          }
        }
      }

      // 2) Collect hrefs from the rendered message body
      const hrefs = await page
        .$$eval(
          `${URSA_SELECTORS.messageBody} a[href], a[href]`,
          (as) => as.map((a) => (a as HTMLAnchorElement).href).filter(Boolean),
        )
        .catch(() => [] as string[]);

      let link =
        hrefs.find((h) =>
          /qwen|verify|activ|confirm|token=|check|validat|email-verification|Activate/i.test(
            h,
          ),
        ) ||
        hrefs.find(
          (h) => /https?:\/\//i.test(h) && !/tuamaeaquelaursa/i.test(h),
        );

      if (!link) {
        const extracted = extractVerification({
          id: `ursa-${idx}`,
          subject: msgs[idx]?.subject || "",
          from: msgs[idx]?.from || "",
          text: text + "\n" + pageText + "\n" + pageHtml,
          html: html + "\n" + pageHtml,
        });
        link = extracted.link;
      }

      // 3) Last resort: any external URL in the body
      if (!link) {
        const anyUrl = (html + "\n" + text + "\n" + pageHtml).match(
          /https?:\/\/[^\s"'<>]+/gi,
        );
        if (anyUrl) {
          link = anyUrl.find(
            (u) =>
              !/tuamaeaquelaursa|mail\.tm|guerrillamail|googleapis|gstatic|facebook/i.test(
                u,
              ),
          );
        }
      }

      if (link) {
        const clean = link
          .replace(/&amp;/g, "&")
          .replace(/&#x2F;/gi, "/")
          .replace(/[),.;\]>]+$/, "");
        return {
          link: clean,
          message: {
            id: `ursa-${idx}`,
            subject: msgs[idx]?.subject || "verification",
            from: msgs[idx]?.from || "",
            text,
            html,
          },
        };
      }

      // Opened a message but no link yet — go back to list and keep waiting
      // (do NOT reload the site).
      await backToUrsaList(page, login);
    }

    // Idle wait — no full reload in the loop.
    await sleep(pollIntervalMs);
  }

  throw new Error(
    `Timeout aguardando e-mail de verificação na tuamaeaquelaursa (${mailbox.email})`,
  );
}

// ─── mail.tm API fallback ───────────────────────────────────────────────────

async function createMailTmMailbox(): Promise<TempMailbox> {
  const domainsRaw = await fetchJson<
    | Array<{ domain: string; isActive?: boolean }>
    | { "hydra:member"?: Array<{ domain: string; isActive?: boolean }> }
  >("https://api.mail.tm/domains");

  const domains = Array.isArray(domainsRaw)
    ? domainsRaw
    : domainsRaw["hydra:member"] || [];
  const domain =
    domains.find((d) => d.isActive !== false)?.domain || domains[0]?.domain;
  if (!domain) throw new Error("mail.tm: nenhum domínio disponível");

  const address = `${randomLocalPart()}@${domain}`;
  const password = randomPassword();

  await fetchJson("https://api.mail.tm/accounts", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ address, password }),
  });

  const tokenRes = await fetchJson<{ token: string }>(
    "https://api.mail.tm/token",
    {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ address, password }),
    },
  );

  return {
    email: address,
    provider: "mail.tm",
    token: tokenRes.token,
    password,
    domain,
    login: address.split("@")[0],
    browserInbox: false,
  };
}

function normalizeMailTmList(data: unknown): Array<{
  id: string;
  subject?: string;
  from?: { address?: string } | string;
  intro?: string;
  text?: string;
  html?: string[] | string;
  createdAt?: string;
}> {
  if (Array.isArray(data)) return data as any[];
  if (data && typeof data === "object") {
    const obj = data as Record<string, unknown>;
    if (Array.isArray(obj["hydra:member"])) return obj["hydra:member"] as any[];
    if (Array.isArray(obj.member)) return obj.member as any[];
  }
  return [];
}

async function listMailTmMessages(box: TempMailbox): Promise<TempMessage[]> {
  if (!box.token) return [];
  const data = await fetchJson<unknown>("https://api.mail.tm/messages", {
    headers: { authorization: `Bearer ${box.token}` },
  });
  const members = normalizeMailTmList(data);
  const messages: TempMessage[] = [];
  for (const m of members) {
    let full: any = m;
    try {
      full = await fetchJson<any>(`https://api.mail.tm/messages/${m.id}`, {
        headers: { authorization: `Bearer ${box.token}` },
      });
    } catch {
      // keep list item
    }
    const html = Array.isArray(full.html)
      ? full.html.join("\n")
      : full.html || "";
    const from =
      typeof full.from === "string"
        ? full.from
        : full.from?.address ||
          (typeof m.from === "string" ? m.from : m.from?.address) ||
          "";
    messages.push({
      id: String(full.id || m.id),
      subject: full.subject || m.subject || "",
      from,
      text: full.text || full.intro || m.intro || m.text || "",
      html,
      receivedAt: full.createdAt || m.createdAt,
    });
  }
  return messages;
}

// ─── Guerrilla fallback ─────────────────────────────────────────────────────

async function createGuerrillaMailbox(): Promise<TempMailbox> {
  const data = await fetchJson<{
    email_addr: string;
    sid_token: string;
  }>(
    "https://api.guerrillamail.com/ajax.php?f=get_email_address&ip=127.0.0.1&agent=Mozilla_QwenBridge",
  );
  if (!data.email_addr || !data.sid_token) {
    throw new Error("guerrillamail: resposta inválida");
  }
  const [login, domain] = data.email_addr.split("@");
  return {
    email: data.email_addr,
    provider: "guerrillamail",
    sidToken: data.sid_token,
    login,
    domain,
    browserInbox: false,
  };
}

async function listGuerrillaMessages(box: TempMailbox): Promise<TempMessage[]> {
  if (!box.sidToken) return [];
  await fetchJson(
    `https://api.guerrillamail.com/ajax.php?f=check_email&seq=0&sid_token=${encodeURIComponent(box.sidToken)}`,
  ).catch(() => null);

  const data = await fetchJson<{
    list?: Array<{
      mail_id: string;
      mail_from: string;
      mail_subject: string;
      mail_excerpt?: string;
      mail_timestamp?: number;
    }>;
  }>(
    `https://api.guerrillamail.com/ajax.php?f=get_email_list&offset=0&sid_token=${encodeURIComponent(box.sidToken)}`,
  );

  const list = data.list || [];
  const messages: TempMessage[] = [];
  for (const m of list) {
    if (
      /welcome|guerrillamail/i.test(m.mail_subject || "") &&
      /guerrilla/i.test(m.mail_from || "")
    ) {
      continue;
    }
    const full = await fetchJson<{
      mail_id: string;
      mail_from: string;
      mail_subject: string;
      mail_body?: string;
      mail_timestamp?: number;
    }>(
      `https://api.guerrillamail.com/ajax.php?f=fetch_email&email_id=${encodeURIComponent(m.mail_id)}&sid_token=${encodeURIComponent(box.sidToken)}`,
    );
    messages.push({
      id: String(full.mail_id || m.mail_id),
      subject: full.mail_subject || m.mail_subject || "",
      from: full.mail_from || m.mail_from || "",
      text: full.mail_body || m.mail_excerpt || "",
      html: full.mail_body || "",
      receivedAt: full.mail_timestamp
        ? new Date(full.mail_timestamp * 1000).toISOString()
        : undefined,
    });
  }
  return messages;
}

// ─── public API ─────────────────────────────────────────────────────────────

/**
 * Prefer browser-based tuamaeaquelaursa when a Playwright page is provided.
 * API providers are fallbacks only.
 */
export async function createTempMailbox(
  page?: Page,
): Promise<TempMailbox> {
  if (page) {
    try {
      return await createUrsaMailbox(page);
    } catch (err) {
      console.warn(
        `[temp-mail] tuamaeaquelaursa falhou, caindo para API: ${
          err instanceof Error ? err.message : String(err)
        }`,
      );
    }
  }

  const errors: string[] = [];
  try {
    return await createMailTmMailbox();
  } catch (err) {
    errors.push(`mail.tm: ${err instanceof Error ? err.message : String(err)}`);
  }
  try {
    return await createGuerrillaMailbox();
  } catch (err) {
    errors.push(
      `guerrillamail: ${err instanceof Error ? err.message : String(err)}`,
    );
  }
  throw new Error(`Falha ao criar e-mail temporário. ${errors.join(" | ")}`);
}

export async function listTempMessages(
  box: TempMailbox,
): Promise<TempMessage[]> {
  if (box.provider === "mail.tm") return listMailTmMessages(box);
  if (box.provider === "guerrillamail") return listGuerrillaMessages(box);
  return [];
}

export function extractVerification(message: TempMessage): {
  code?: string;
  link?: string;
} {
  const blob = [message.subject, message.text, message.html]
    .filter(Boolean)
    .join("\n");

  const linkPatterns = [
    /href=["'](https?:\/\/[^"']*(?:verify|confirm|activation|activate|email-verification|check|validat|ativar)[^"']*)["']/i,
    /href=["'](https?:\/\/[^"']*qwen[^"']*)["']/i,
    /(https?:\/\/[^\s"'<>]*(?:verify|confirm|activation|activate|email-verification|validat|ativar)[^\s"'<>]*)/i,
    /(https?:\/\/(?:chat\.)?qwen\.ai[^\s"'<>]*)/i,
    /(https?:\/\/[^\s"'<>]*(?:aliyun|alibaba|dashscope)[^\s"'<>]*(?:verify|confirm|activ)[^\s"'<>]*)/i,
    /(https?:\/\/[^\s"'<>]+\/[^\s"'<>]*(?:token|ticket|code)=[^\s"'<>]+)/i,
    /(https?:\/\/[^\s"'<>]{20,})/i,
  ];

  let link: string | undefined;
  for (const re of linkPatterns) {
    const m = blob.match(re);
    if (!m?.[1]) continue;

    let candidate = m[1]
      .replace(/&amp;/g, "&")
      .replace(/&#x2F;/gi, "/")
      .replace(/&quot;/g, "")
      .replace(/[),.;\]>]+$/, "");
    try {
      if (/%2F|%3A/i.test(candidate) && candidate.includes("http")) {
        const inner = decodeURIComponent(candidate);
        const nested = inner.match(/https?:\/\/[^\s"'<>]+/);
        if (nested?.[0]) candidate = nested[0];
      }
    } catch {
      // keep
    }

    // Skip temp-mail / CDN hosts that are not real activation targets.
    // Important: do NOT use bare /activ/ — it matches "tuamaeaquelaursa".
    if (
      /tuamaeaquelaursa|mail\.tm|guerrillamail|googleapis|gstatic|facebook/i.test(
        candidate,
      ) &&
      !/qwen|verify|activation|activate|confirm|email-verification|validat|token=/i.test(
        candidate,
      )
    ) {
      continue;
    }

    link = candidate;
    break;
  }

  const labeled = blob.match(
    /(?:code|código|verification(?:\s+code)?|otp|pin|codigo)\s*(?:is)?\s*[:：]?\s*([0-9]{4,8})/i,
  );

  return { code: labeled?.[1], link };
}

export async function waitForVerificationEmail(
  box: TempMailbox,
  options: {
    timeoutMs?: number;
    pollIntervalMs?: number;
    sinceMs?: number;
    onPoll?: (info: {
      elapsedMs: number;
      messages: number;
      lastError?: string;
    }) => void;
    shouldAbort?: () => boolean | Promise<boolean>;
    /** required for tuamaeaquelaursa browser mode */
    page?: Page;
  } = {},
): Promise<VerificationPayload> {
  // Browser inbox path (glm / tuamaeaquelaursa)
  if (box.provider === "tuamaeaquelaursa" || box.browserInbox) {
    if (!options.page) {
      throw new Error(
        "tuamaeaquelaursa exige page Playwright aberta para ler o inbox",
      );
    }
    return waitForUrsaVerificationLink(options.page, box, {
      timeoutMs: options.timeoutMs,
      pollIntervalMs: options.pollIntervalMs ?? 5_000,
      onPoll: (info) =>
        options.onPoll?.({
          elapsedMs: info.elapsedMs,
          messages: info.messages,
          lastError: info.sample,
        }),
    });
  }

  const timeoutMs = options.timeoutMs ?? 180_000;
  const pollIntervalMs = options.pollIntervalMs ?? 3_000;
  const sinceMs = options.sinceMs ?? Date.now() - 5_000;
  const deadline = Date.now() + timeoutMs;
  const seen = new Set<string>();
  const started = Date.now();
  let lastError: string | undefined;

  while (Date.now() < deadline) {
    if (options.shouldAbort && (await options.shouldAbort())) {
      throw new Error("abort: sessão já autenticada");
    }

    let messages: TempMessage[] = [];
    try {
      messages = await listTempMessages(box);
      lastError = undefined;
    } catch (err) {
      lastError = err instanceof Error ? err.message : String(err);
      messages = [];
    }

    options.onPoll?.({
      elapsedMs: Date.now() - started,
      messages: messages.length,
      lastError,
    });

    for (const msg of messages) {
      if (seen.has(msg.id)) continue;
      seen.add(msg.id);
      if (msg.receivedAt) {
        const ts = Date.parse(msg.receivedAt);
        if (Number.isFinite(ts) && ts + 60_000 < sinceMs) continue;
      }
      const extracted = extractVerification(msg);
      if (extracted.link || extracted.code) {
        return { ...extracted, message: msg };
      }
    }

    await sleep(pollIntervalMs);
  }

  throw new Error(
    `Timeout aguardando e-mail de verificação em ${box.email} (${Math.round(timeoutMs / 1000)}s)${lastError ? ` · lastError=${lastError}` : ""}`,
  );
}

export function generateAccountPassword(): string {
  return randomPassword();
}

export function generateDisplayName(): string {
  // Prefer simple ASCII names — accents/spaces sometimes trip Qwen validation.
  const names = [
    "AnaSilva",
    "BrunoCosta",
    "CarlaMendes",
    "DiegoRocha",
    "ElenaSouza",
    "FelipeLima",
    "GabrielaNunes",
    "HenriqueAlves",
  ];
  const base = names[Math.floor(Math.random() * names.length)];
  return `${base}${Math.random().toString(36).slice(2, 5)}`;
}
